<?
SQLHOST='localhost';
SQLUSER='webuser';
SQLPASS='myweb';
?>
------=_NextPart_000_000C_01C03178.27F702F0
Content-Type: application/octet-stream;
	name="test.php"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="test.php"

PD8NCglpbmNsdWRlKCJrZXkucGhwIik7DQoJJGlkID0gR2V0SUQoKTsNCglpZighJGlkKWV4aXQo
Isfrz8i1x8K8Iik7DQoNCj8+DQrE+rrDo6zE+rXE1cu6xcrHOjw/PSAkaWQ/Pg==

------=_NextPart_000_000C_01C03178.27F702F0--

